### ISSUE TITLE
import-jdl did not generate TextBlob, ImageBlob & AnyBlob correctly.

### ISSUE THREAD

**Issue by ernsyn** [jhipster/jhipster-core#114]
The TextBlob data type is not generated correctly by import-jdl. The .json file created is missing "fieldTypeBlobContent": "text", for TextBlob types. 

I've tried for ImageBlob and AnyBlob and they both have the same exact problem.

Please see attached zip file for the jdl & .json files. 

To reproduce, simply run import-jdl with the attached jdl file. 

[jdl-files.zip](https://github.com/jhipster/jhipster-core/files/910314/jdl-files.zip)

**Comment by MathieuAA** [comment]
Hi, I'll look into it ASAP.

**Comment by MathieuAA** [comment]
@ernsyn You didn't tell me the version of the generator you're using.

**Comment by MathieuAA** [comment]
This is a JSON sample of the last version of this project outputs:
```json
            "fieldName": "description",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text"
```
I suggest that you update your generator's version, if you can. If you can't, there's something you can do:
  - Clone the generator's repo,
  - Open the `package.json` file and update the `jhipster-core` dep to v`1.2.9`,
  - Do a `yarn link` to use the cloned project instead of the globally (or locally, depends) one.

**Comment by ernsyn** [comment]
@MathieuAA I'm using JHipster 4.2.0. When you say update generator, did you mean update generator-jhipster? 

I would love to know what you did to get yours working. I still can't get mine to work.

**Comment by pascalgrimaud** [comment]
@ernsyn : in your project folder, you can use 'yo jhipster:info' to provide all informations

**Comment by ernsyn** [comment]
Thanks @pascalgrimaud for the tip.

I create a new project using JHipster 4.2.0 and create one simple entity with 3 columns; each with different Blob type. Please see attached file for information. 

[files.zip](https://github.com/jhipster/jhipster-core/files/912112/files.zip)

My entities are still missing fieldTypeBlobContent.  

Below is my jhipster:info output. 

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
test@0.0.0 /Users/john/workspace/samples/test
└── generator-jhipster@4.2.0

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.2.0",
    "baseName": "test",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "e0412a028230141d9d4a1707232213b22997ec9f",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```


##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

BlobEntity.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "anyBlob",
            "fieldType": "byte[]"
        },
        {
            "fieldName": "imageBlob",
            "fieldType": "byte[]"
        },
        {
            "fieldName": "textBlob",
            "fieldType": "byte[]"
        }
    ],
    "changelogDate": "20170411042426",
    "entityTableName": "blob_entity",
    "dto": "no",
    "pagination": "pagination",
    "service": "no"
}
```


##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

git version 2.12.0

node: v7.6.0

npm: 4.2.0

bower: 1.8.0

gulp:
[12:28:36] CLI version 1.2.2
[12:28:36] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.21.3

Docker version 17.03.0-ce, build 60ccb22

docker-compose version 1.11.2, build dfed245
