### ISSUE TITLE
too many space and wrap when i use yo jhipster:import-jdl generate entity

### ISSUE THREAD

**Issue by anjia0532** [jhipster/jhipster-core#73]
https://jhipster.github.io/jdl/#a-namecommentingjdla-commenting--javadoc support java-doc it's so cool,but something is wrong with the `yo jhipster:import-jdl`

jdl code like this
```
/**
 * blog demo
 */
entity Blog {
   /**
     * author's name
     */
   name String required
}
```

generator Blog.java like this

```java

/**
 * blog demo                                                                          //(about 70 space)
 * 
 */
@ApiModel(description = ""
    + "blog demo                              "
    + "")
@Entity
@Table(name = "blog")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Blog implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /**
     * author's name                                                      
     * 
     */
    @ApiModelProperty(value = ""
        + "author's name                                                 "
        + "")
    @NotNull
    @Column(name = "name", nullable = false)
    private String name;
```

it has too many space and wrap to manual remove it

**Comment by MathieuAA** [comment]
I'll test this... but I doubt it's my fault.

**Comment by anjia0532** [comment]
@MathieuAA 
thanks, that's my jhipster info 




##### **JHipster Version(s)**

```
gateway@0.0.0 \path\jhipster\jhipster\gateway
`-- generator-jhipster@3.9.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "gateway",
    "packageName": "com.shunneng.gateway",
    "packageFolder": "com/shunneng/gateway",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
##### **Browsers and Operating System**

java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

git version 2.10.1.windows.1

node: v6.3.1

npm: 3.10.6

bower: 1.7.9

gulp:
[21:19:33] CLI version 3.9.1
[21:19:33] Local version 3.9.1

yeoman: 1.8.5

Docker version 1.12.2-rc1, build 45bed2c, experimental

docker-compose version 1.8.1, build 004ddae
