### ISSUE TITLE
multiline comments are merged into single row

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/jhipster-core#87]
##### **Overview of the issue**

If writing multiline javadoc comments in JDL Studio then these are converted into single line in final domain class javadoc comment.

##### **Motivation for or Use Case**

I have many multiline comments in my .jh file. I don't want edit these comments (wrap into multiple lines) in generated domain class.

##### **Reproduce the error**

1. Add comment to .jh file in the form:
```
/**
 * First line of the comment.
 * Second line of the comment.
 */
```
2. Generate entities from .jh file:
```
yo jhipster:import-jdl entity.jh 
```
3. Result in the domain class is:
```
/**
 * First line of the comment.Second line of the comment.
 */
```

##### **Suggest a Fix**

Keep newlines in javadoc fields.
I prepared functionality in PR jhipster/generator-jhipster#4561
I'll do soon PR for fix which relies on this previous PR.
So after jhipster/generator-jhipster#4561 is merged my new PR can be merged.

##### **JHipster Version(s)**

```
jhipster@0.0.0 c:\projects\kaido-github\jhipster-test-global
`-- generator-jhipster@3.11.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.11.0",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "rememberMeKey": "7c94f57335132b1bebf40a99c2dd751d2a359367",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Region.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "regionName",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20161128010824",
    "javadoc": "First line.Second line.",
    "entityTableName": "region",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.7.0.windows.1

node: v6.9.1

npm: 3.10.9

bower: 1.8.0

gulp:
[03:10:28] CLI version 1.2.2
[03:10:28] Local version 3.9.1

yeoman: 1.8.5
